In [1]:
print("Hello world")


Hello world


In [2]:
# load an example dataset
from vega_datasets import data
cars = data.cars()

import altair as alt

interval = alt.selection_interval()

alt.Chart(cars).mark_point().encode(
  x='Horsepower',
  y='Miles_per_Gallon',
  color=alt.condition(interval, 'Origin', alt.value('lightgray'))
).properties(
  selection=interval
)

alt.Chart(...)

In [13]:
import torch 
from sklearn.datasets import load_boston
import numpy as np
print(torch.__version__)

1.10.0+cu111


In [14]:
x=torch.rand(10)
print(x)
print(x.size)
print(x.size())
#array boyutunu belirleyebildik.


tensor([0.0784, 0.9794, 0.2729, 0.0240, 0.2641, 0.2638, 0.5270, 0.9222, 0.6724,
        0.7119])
<built-in method size of Tensor object at 0x7f2150073cb0>
torch.Size([10])


In [15]:
temp=torch.FloatTensor([23,24,25,23.4,546,45])
print(temp)
print(temp.size())

tensor([ 23.0000,  24.0000,  25.0000,  23.4000, 546.0000,  45.0000])
torch.Size([6])


In [19]:
bostonhouses=load_boston()

print(bostonhouses.data)
bostonhouses=torch.from_numpy(bostonhouses.data)
print(bostonhouses)
#tensör=> 3 boyutlu matris diyebiliirz.
print("--------------")
print(bostonhouses.size())
#13 evimiz 5036 tane de özelliğimiz olduğunu gösterir.
print(bostonhouses[0:2].size())

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
tensor([[6.3200e-03, 1.8000e+01, 2.3100e+00,  ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00,  ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00,  ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01,  ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01,  ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01,  ..., 2.1000e

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

# *Array işlemleri* 


In [31]:
#resim dosyası yükleme
from google.colab import files
from IPython.display import Image
from matplotlib import pyplot as plt
uploaded = files.upload()


Saving puf.png to puf (1).png


In [39]:
from PIL import Image
import numpy as np
kedi=np.array(Image.open("puf.png").resize((224,224)))
print(kedi)
print(np.shape(kedi))
#resmi torch arrayine çevirme işlemini gerçekleştirdik.
#numpy array torch array çevirmek lazım.
keditorch=torch.from_numpy(kedi)
print(keditorch.size())
#Çalışmadı
#plt.imsave('kediciktorch',keditorch)


[[7 7 7 ... 7 7 0]
 [7 7 7 ... 7 7 0]
 [7 7 7 ... 7 7 0]
 ...
 [0 0 0 ... 0 0 7]
 [0 0 0 ... 0 0 7]
 [0 0 0 ... 0 0 7]]
(224, 224)
torch.Size([224, 224])


Array işlemleri/**CUDA**

In [44]:
#torch formatındaki iki array arasında matematiksel işlemleri yapılabiliyor. fakat
#fonk kullanımının daha effective olduğunu söyleyebiliriz.

rand1=torch.rand(2,2)
rand2=torch.rand(2,2)
print(rand1,rand2)
print(rand1+rand2)
print(torch.add(rand1,rand2))
print(rand1*rand2)
print(rand1.mul(rand2))
print("*****************")
print(rand1)
print("-------------")
print(rand1.mul(5))






tensor([[0.3091, 0.4767],
        [0.0314, 0.6276]]) tensor([[0.9621, 0.1932],
        [0.5498, 0.7223]])
tensor([[1.2712, 0.6699],
        [0.5812, 1.3499]])
tensor([[1.2712, 0.6699],
        [0.5812, 1.3499]])
tensor([[0.2974, 0.0921],
        [0.0172, 0.4533]])
tensor([[0.2974, 0.0921],
        [0.0172, 0.4533]])
*****************
tensor([[0.3091, 0.4767],
        [0.0314, 0.6276]])
-------------
tensor([[1.5456, 2.3833],
        [0.1568, 3.1380]])


**# Cuda işlemlerine giriş**

In [45]:
#GPU nun sağladığı performansı görebiliriz.
#bu işlem baya uzun sürdü.
rand1=torch.rand(10000,10000)
rand2=torch.rand(10000,10000)
print(".")
rand1.matmul(rand2)
print("...")

.
...


In [ ]:
#bu işlemle bize daha cok zaman kazandırmaktadır.
#.cuda() ile gpu da kullanılır
rand1=rand1.cuda()
rand2=rand2.cuda()





In [51]:
from torch.autograd import Variable
x=Variable(torch.randn(1,10))
prev_h=Variable(torch.randn(1,20))
W_h=Variable(torch.randn(20,20))
W_x=Variable(torch.randn(20,10))

i2h=torch.mm(W_x,x.t())
h2h=torch.mm(W_h,prev_h.t())

next_h=i2h+h2h
next_h=next_h.tanh()

print(next_h)

#next_h.backward(torch.ones(1,20))

tensor([[ 0.7790],
        [-0.9949],
        [ 1.0000],
        [-0.9827],
        [-0.9991],
        [-0.9999],
        [-0.9918],
        [-0.9367],
        [ 0.9052],
        [-1.0000],
        [ 0.3942],
        [-0.9081],
        [-0.7170],
        [-1.0000],
        [-0.8353],
        [ 1.0000],
        [-1.0000],
        [-0.9999],
        [-0.7797],
        [ 1.0000]])


**Lineer regresyon**